### ISSUE TITLE
Not set PRETRAINED_MODEL in some configs.

### ISSUE THREAD

**Issue by serend1p1ty** [modelscope/scepter#29]
I found PRETRAINED_MODEL is empty in some configs, e.g., `scepter/methods/scedit/ctr/sd21_768_sce_ctr_canny.yaml`

Is it by design?

```
COND_STAGE_MODEL:
      NAME: FrozenOpenCLIPEmbedder
      ARCH: ViT-H-14
      PRETRAINED_MODEL:
      LAYER: penultimate
```
